name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Q01
      id: q01
      uses: education/autograding-command-grader@v1
      with:
        test-name: Q01
        setup-command: " sudo -H pip3 install automata-lib parameterized"
        command: python -m unittest -v test/test_Q01.py
        timeout: 10
        max-score: 5
    - name: Q02
      id: q02
      uses: education/autograding-command-grader@v1
      with:
        test-name: Q02
        setup-command: " sudo -H pip3 install automata-lib parameterized"
        command: python -m unittest -v test/test_Q02.py
        timeout: 10
        max-score: 10
    - name: Q03
      id: q03
      uses: education/autograding-command-grader@v1
      with:
        test-name: Q03
        setup-command: sudo -H pip3 install automata-lib parameterized
        command: python -m unittest -v test/test_Q03.py
        timeout: 10
        max-score: 5
    - name: Q04
      id: q04
      uses: education/autograding-command-grader@v1
      with:
        test-name: Q04
        setup-command: sudo -H pip3 install automata-lib parameterized
        command: " python -m unittest -v test/test_Q04.py"
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        Q01_RESULTS: "${{steps.q01.outputs.result}}"
        Q02_RESULTS: "${{steps.q02.outputs.result}}"
        Q03_RESULTS: "${{steps.q03.outputs.result}}"
        Q04_RESULTS: "${{steps.q04.outputs.result}}"
      with:
        runners: q01,q02,q03,q04
